source/accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView, UpdateFamilyView, logout_view,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', logout_view, name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/family/', UpdateFamilyView.as_view(), name='update_family'),

    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

source/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
    path('asset/', include('asset.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/asset/urls.py
from django.urls import path

from asset.views import InsertActivityView
from asset import views
from asset.views import ListActivityView, NetAssetHistoryView
from asset.views import InvestmentView


app_name = "asset"

urlpatterns = [
    path("insert-new-activity/", InsertActivityView.as_view(), name="new_activity"),
    path("history-activity/", ListActivityView.as_view(), name="history_activity"),
    path("ajax/load-cities/", views.load_category, name="ajax_load_category"),
    path(
        "asset-liquidation-process",
        views.AssetLiquidationProcessView.as_view(),
        name="asset_liquidation_process",
    ),
    path("net-asset-history", NetAssetHistoryView.as_view(), name="net_asset_history"),
    path("investment", InvestmentView.as_view(), name="investment"),
]

source/content/templates/layouts/default/page.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}

{% get_current_language as language_code %}

<!DOCTYPE html>
<html lang="{{ language_code }}">

<head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="An example of Django project with basic user functionality.">
    <meta name="author" content="Yehor Smoliakov">

    <link rel="icon" href="{% static 'favicon.ico' %}">

    <title>AMS</title>

    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">

</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-to">
    <a class="navbar-brand" href="{% url 'asset:new_activity' %}">Trang chủ</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">

            {% if request.user.is_authenticated %}
                {% if request.user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'asset:new_activity' %}">{% trans 'Django administration' %}</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'asset:investment' %}">Đầu tư</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'asset:history_activity' %}">Lịch sử giao dịch</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'asset:asset_liquidation_process' %}">Tất toán đầu tư</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Thanh toán nợ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'asset:net_asset_history' %}">Thông tin tài sản và nợ</a>
                </li>
                
                <li class="nav-item dropdown mr-auto">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Cài đặt
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'accounts:change_password' %}">Đổi mật khẩu</a>
                        <a class="dropdown-item" href="{% url 'accounts:change_profile' %}">Thông tin cá nhân</a>
                        <a class="dropdown-item" href="{% url 'accounts:update_family' %}">Thông tin gia đình</a>
                        <a class="dropdown-item" href="{% url 'accounts:change_email' %}">Đổi email</a>
                        <a class="dropdown-item" href="{% url 'accounts:log_out' %}">Đăng xuất</a>
                    </div>
                </li>

            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:log_in' %}">Đăng nhập</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:sign_up' %}">Đăng ký</a>
                </li>
            {% endif %}

            
        </ul>
    </div>
</nav>


    <div class="container-fluid mt-3">

        {% bootstrap_messages %}

        {% block content %}
        No content.
        {% endblock %}

    </div>

    <script src="{% static 'vendor/jquery/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'vendor/popper/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>



</body>

</html>