source/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
    path('asset/', include('asset.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/asset/urls.py
from django.urls import path

from asset.views import InsertActivityView
from asset import views
from asset.views import ListActivityView, NetAssetHistoryView
from asset.views import InvestmentView


app_name = "asset"

urlpatterns = [
    path("insert-new-activity/", InsertActivityView.as_view(), name="new_activity"),
    path("history-activity/", ListActivityView.as_view(), name="history_activity"),
    path("ajax/load-cities/", views.load_category, name="ajax_load_category"),
    path(
        "asset-liquidation-process",
        views.AssetLiquidationProcessView.as_view(),
        name="asset_liquidation_process",
    ),
    path("net-asset-history", NetAssetHistoryView.as_view(), name="net_asset_history"),
    path("investment", InvestmentView.as_view(), name="investment"),
]

source/asset/models.py
from django.db import models
from accounts.models import MyUser
from djmoney.models.fields import MoneyField


EXPENSE = "EXPENSE"
INCOME = "INCOME"

ACTIVITY_TYPE_CHOICES = [(EXPENSE, "Chi"), (INCOME, "Thu")]


FINANCIAL_ASSETS = "FINANCIAL_ASSETS"
REAL_ESTATE = "REAL_ESTATE"
CASH = "CASH"
FIXED_TERM_SAVINGS = "FIXED_TERM_SAVINGS"
OTHERS = "OTHERS"
ASSERT_CATEGORIES = [
    (CASH, "Tiền mặt"),
    (FIXED_TERM_SAVINGS, "Sổ tiết kiệm"),
    (FINANCIAL_ASSETS, "Tài sản tài chính"),
    (REAL_ESTATE, "Bất động sản"),
    (OTHERS, "Khác"),
]

CREDIT_CARD = "CREDIT CARD"
SHORT_TERM_DEBT = "SHORT-TERM DEBT"
LONG_TERM_DEBT = "LONG-TERM DEBT"
CASH = "CASH"

FUNDING_SOURCE_CATEGORIES = [
    (CASH, "Tiền mặt"),
    (CREDIT_CARD, "Thẻ tín dụng"),
    (SHORT_TERM_DEBT, "Khoản nợ ngắn hạn"),
    (LONG_TERM_DEBT, "Khoản nợ giải hạn"),
]


class ActivityCategory(models.Model):
    name = models.TextField(max_length=200, blank=False)
    activity_type = models.CharField(
        max_length=10,
        choices=ACTIVITY_TYPE_CHOICES,
        default=EXPENSE,
    )

    def __str__(self):
        return self.name


class Asset(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    name = models.TextField(max_length=200, blank=False)
    amount = MoneyField(max_digits=19, decimal_places=2, default_currency="VND")
    category = models.CharField(
        max_length=50,
        choices=ASSERT_CATEGORIES,
        default=CASH,
    )

    def __str__(self):
        return self.name

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Liability(models.Model):
    CREDIT_CARD = "CREDIT CARD"
    SHORT_TERM_DEBT = "SHORT-TERM DEBT"
    LONG_TERM_DEBT = "LONG-TERM DEBT"

    LIABILITY_CATEGORIES = [
        (CREDIT_CARD, CREDIT_CARD),
        (SHORT_TERM_DEBT, SHORT_TERM_DEBT),
        (LONG_TERM_DEBT, LONG_TERM_DEBT),
    ]
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    name = models.TextField(max_length=200, blank=False)
    amount = MoneyField(max_digits=19, decimal_places=2, default_currency="VND")
    category = models.CharField(
        max_length=50,
        choices=LIABILITY_CATEGORIES,
        default=CREDIT_CARD,
    )

    def __str__(self):
        return self.name

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Activity(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    activity_type = models.CharField(
        max_length=10,
        choices=ACTIVITY_TYPE_CHOICES,
        default=EXPENSE,
    )
    category = models.ForeignKey(ActivityCategory, on_delete=models.CASCADE)
    input_date = models.DateField()
    amount = MoneyField(max_digits=19, decimal_places=2, default_currency="VND")

    
    funding_sources = models.CharField(
        max_length=50,
        choices=FUNDING_SOURCE_CATEGORIES,
        default=CASH,
    )
    notes = models.TextField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class NetAssetHistory(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    month = models.DateField()
    asset_amount = MoneyField(max_digits=19, decimal_places=2, default_currency="VND")
    liability_amount = MoneyField(max_digits=19, decimal_places=2, default_currency="VND")


    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def net_value(self):
        return self.asset_amount - self.liability_amount
    
    def to_dict(self): 
        return {
            "month": self.month.strftime("%Y-%m"),
            "asset": int(self.asset_amount.amount),
            "liability": int(self.liability_amount.amount),
            "net": int(self.net_value().amount)
        }


    

source/asset/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from django.db.models import Q
from datetime import datetime

from asset.models import Activity, ActivityCategory
from asset.models import EXPENSE

from django.forms import Select
from django.conf import settings
from djmoney.forms import MoneyWidget
from asset.models import Asset
from asset.models import CASH
from asset.models import ASSERT_CATEGORIES
from asset.models import FUNDING_SOURCE_CATEGORIES

User = get_user_model()


class UserCacheMixin:
    user_cache = None


class DateInput(forms.DateInput):
    input_type = "date"


class BlankWidget(Select):
    template_name = "asset/django-money/fake-widget.html"


class NoCurrencyMoneyWidget(MoneyWidget):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs, currency_widget=BlankWidget)

    def value_from_datadict(self, data, files, name):
        val = super().value_from_datadict(data, files, name)
        if val[1] is None:
            val[1] = settings.DEFAULT_CURRENCY
        return val


class InvestmentForm(forms.Form):
    investment_day = forms.DateField(
        label="Ngày đầu tư", widget=forms.widgets.DateInput(attrs={"type": "date"})
    )
    investment_money = forms.CharField(label="Số tiền đầu tư")
    asset_type = forms.CharField(
        label="Loại tài sản đầu tư", widget=forms.Select(choices=ASSERT_CATEGORIES[1:])
    )
    funding_source = forms.CharField(
        label="Nguồn tiền", widget=forms.Select(choices=FUNDING_SOURCE_CATEGORIES)
    )

    notes = forms.CharField(label="Ghi chú")


class InsertActivityForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if "activity_type" in self.data:
            try:
                activity_type = self.data.get("activity_type")
                self.fields["category"].queryset = ActivityCategory.objects.filter(
                    activity_type=activity_type
                ).order_by("id")
            except (ValueError, TypeError):
                pass
        else:
            self.fields["category"].queryset = ActivityCategory.objects.filter(
                activity_type=EXPENSE
            ).order_by("id")

    class Meta:
        model = Activity
        fields = [
            "activity_type",
            "category",
            "input_date",
            "amount",
            "funding_sources",
            "notes",
        ]

        widgets = {
            "input_date": DateInput(),
            "notes": forms.Textarea(attrs={"rows": 1}),
            "amount": NoCurrencyMoneyWidget,
        }
        field_order = fields
        labels = {
            "activity_type": "Họat động",
            "category": "Danh mục",
            "input_date": "Ngày thực hiện",
            "amount": "Số tiền",
            "funding_sources": "Nguồn tiền",
            "notes": "Ghi chú",
        }


class AssetLiquidationProcessForm(forms.Form):
    asset = forms.ModelChoiceField(queryset=None, label="Chọn tài sản muốn tất toán")
    liquidation_value = forms.CharField(label="Số tiền thu về")
    residual_value = forms.CharField(label="Giá trị tài sản còn lại")

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["asset"].queryset = Asset.objects.filter(
            Q(user=user), ~Q(category=CASH)
        )

source/asset/templates/asset/asset_liquidation_process.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}


<div class="row">
    <div class="col-xl-3"></div>
    <div class="col-xl-6 mb-4">
        <form method="post" id="asset_liqudation_form" class="form-horizontal" novalidate>

            {% csrf_token %}
            {% bootstrap_form form %}

            <button class="btn btn-primary">Thêm</button>

        </form>
    </div>
    <div class="col-xl-3"></div>
</div>


<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    (function ($, undefined) {

        "use strict";

        // When ready.
        $(function () {

            var $form = $("#asset_liqudation_form");
            var $input = $form.find('input[type="number"]');

            //*[@id="id_liquidation_value"]

            $input.on("keyup", function (event) {


                // When user select text in the document, also abort.
                var selection = window.getSelection().toString();
                if (selection !== '') {
                    return;
                }

                // When the arrow keys are pressed, abort.
                if ($.inArray(event.keyCode, [38, 40, 37, 39]) !== -1) {
                    return;
                }


                var $this = $(this);

                // Get the value.
                var input = $this.val();

                var input = input.replace(/[\D\s\._\-]+/g, "");
                input = input ? parseInt(input, 10) : 0;

                $this.val(function () {
                    return (input === 0) ? "" : input.toLocaleString("en-US");
                });
            });

            /**
             * ==================================
             * When Form Submitted
             * ==================================
             */
            $form.on("submit", function (event) {
                var rawNumber = $("#id_amount_0").val().replace(/[($)\s\,_\-]+/g, '')
                $("#id_amount_0").val(rawNumber)
            });

        });
    })(jQuery);
</script>

{% endblock %}

source/asset/templates/asset/category_ city_dropdown_list_options.html
{% for category in categories %}
<option value="{{ category.id }}">{{ category.name }}</option>
{% endfor %}

source/asset/templates/asset/investment.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}



<div class="row">
    <div class="col-xl-3"></div>
    <div class="col-xl-6 mb-4">
        <h4>Đầu tư</h4>
    </div>
    <div class="col-xl-3"></div>
</div>


<div class="row">
    <div class="col-xl-3"></div>
    <div class="col-xl-6 mb-4">
        <form method="post" id="investment-form-id"
            class="form-horizontal" novalidate>

            {% csrf_token %}
            {% bootstrap_form form %}

            <button class="btn btn-primary">Thêm</button>

        </form>
    </div>
    <div class="col-xl-3"></div>
</div>


<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    (function ($, undefined) {

        "use strict";

        // When ready.
        $(function () {

            var $form = $("#investment-form-id");
            var $input = $form.find("input[type=text]");

            $input.on("keyup", function (event) {
                
                debugger
                // When user select text in the document, also abort.
                var selection = window.getSelection().toString();
                if (selection !== '') {
                    return;
                }

                debugger
                var $this = $(this);
                if (this.id == "id_notes") return

                console.log("selection:  ", selection)

                // When the arrow keys are pressed, abort.
                if ($.inArray(event.keyCode, [38, 40, 37, 39]) !== -1) {
                    return;
                }


                

                // Get the value.
                var input = $this.val();

                var input = input.replace(/[\D\s\._\-]+/g, "");
                input = input ? parseInt(input, 10) : 0;

                $this.val(function () {
                    return (input === 0) ? "" : input.toLocaleString("en-US");
                });
            });

            /**
             * ==================================
             * When Form Submitted
             * ==================================
             */
            $form.on("submit", function (event) {
                debugger
                var rawNumber = $("input[type=text]").val().replace(/[($)\s\,_\-]+/g, '')
                $("input[type=text]").val(rawNumber)
            });

        });
    })(jQuery);

</script>


{% endblock %}

source/asset/templates/asset/list_activity.html
{% extends 'layouts/default/page.html' %}

{% load static %}
{% load bootstrap4 %}
{% load i18n %}

{% block content %}

<div class="row">
  <div class="col-xl-3"></div>
  <div class="col-xl-6 mb-4">
    <h4>Lịch sử</h4>
  </div>
  <div class="col-xl-3"></div>
</div>


<div class="row">
  <div class="col-xl-3"></div>
  <div class="col-xl-6 mb-4">
    <form action="{% url 'asset:history_activity' %}" method="get" class="form-inline">
      <label class="sr-only" for="inlineFormInputName2">Ngày nhập</label>
      <input type="text" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2" name="datefilter" value=""
        placeholder="Ngày nhập">
      <button type="submit" class="btn btn-primary mb-2">Tìm kiếm</button>
    </form>
  </div>
  <div class="col-xl-3"></div>
</div>

<div class="row">
  <div class="col-xl-3"></div>
  <div class="col-xl-6 mb-4">
    <a class="btn btn-outline-secondary" href="{% url 'asset:history_activity' %}?input_date=last_7_days"
      role="button">7 ngày trước</a>
    <!-- <a class="btn btn-outline-secondary" href="{% url 'asset:history_activity' %}?input_date=last_30_days" role="button">30 ngày trước</a> -->
    <a class="btn btn-outline-secondary" href="{% url 'asset:history_activity' %}?input_date=last_month"
      role="button">Trong tháng trước</a>
  </div>
  <div class="col-xl-3"></div>
</div>



<div class="row">
  <div class="col-xl-3"></div>
  <div class="col-xl-6 mb-4">
    <h5>Tổng quan</h5>
  </div>
  <div class="col-xl-3"></div>
</div>

<div class="row">
  <div class="col-xl-3"></div>
  <div class="col-xl-6 mb-4">
    <canvas id="myChart"></canvas>
  </div>
  <div class="col-xl-3"></div>
</div>

<div class="row">
  <div class="col-xl-3"></div>
  <div class="col-xl-6 mb-4">
    <h5>Danh sách chi tiết</h5>
  </div>
  <div class="col-xl-3"></div>
</div>


{% for activity in page_obj %}
<div class="row">
  <div class="col-xl-3"></div>
  <div class="col-xl-6 mb-4">
    <div class="card">
      <div class="card-body">
        <div class="d-flex justify-content-between align-items-center">
          <div class="d-flex align-items-center">
            <div class="ms-3">
              <p class="fw-bold mb-1">{{activity.user.first_name}} {{activity.user.last_name}}</p>
              <p class="text-muted mb-0">Số tiền: {{activity.amount}}</p>
              <p class="text-muted mb-0">Danh mục: {{activity.category}}</p>
              <p class="text-muted mb-0">Tại ngày: {{activity.input_date|date}}</p>
              <p class="text-muted mb-0">Ghi chú: {{activity.notes}}</p>
            </div>
          </div>
          {% if activity.activity_type == "INCOME" %}
          <span class="badge badge-success">
            THU NHẬP
          </span>
          {% else %}
          <span class="badge badge-danger">
            CHI TIÊU
          </span>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-3"></div>
</div>
{% endfor %}

<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>

<script src="{% static 'vendor/jquery/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'vendor/momentjs/moment.min.js' %}"></script>
<script src="{% static 'vendor/daterangepicker/js/daterangepicker.min.js' %}" defer></script>
<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/css/daterangepicker.css' %}" />


<script type="text/javascript">
  $(function () {

    $('input[name="datefilter"]').daterangepicker({
      autoUpdateInput: false,
      locale: {
        cancelLabel: 'Clear',
        format: "DD/MM/YYYY"
      },

    });

    $('input[name="datefilter"]').on('apply.daterangepicker', function (ev, picker) {
      $(this).val(picker.startDate.format('DD/MM/YYYY') + ' - ' + picker.endDate.format('DD/MM/YYYY'));
    });

    $('input[name="datefilter"]').on('cancel.daterangepicker', function (ev, picker) {
      $(this).val('');
    });
  });
</script>


<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
  const ctx = document.getElementById('myChart').getContext('2d');

  var chart_data = JSON.parse('{{ chart_data_json_str | safe}}');

  var labels = ["Thu nhập", "Chi phí"];
  var data = {
    labels: labels,
    datasets: chart_data
  }

  const config = {
    type: 'bar',
    data: data,
    options: {
      plugins: {
        title: {
          display: true,
          text: 'Thông kê'
        },
      },
      responsive: true,
      scales: {
        x: {
          stacked: true,
        },
        y: {
          stacked: true
        }
      }
    }
  }

  new Chart(ctx, config);
</script>

{% endblock %}

source/asset/templates/asset/net_asset_history.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}


<div class="row">
    <div class="col-xl-3"></div>
    <div class="col-xl-6 mb-4">
        <h5>Tổng quan tài sản và nợ theo tháng</h5>
    </div>
    <div class="col-xl-3"></div>
</div>

<div class="row">
    <div class="col-xl-3"></div>
    <div class="col-xl-6 mb-4">
        <canvas id="net_asset_history_data_chart"></canvas>
    </div>
    <div class="col-xl-3"></div>
</div>


<div class="row">
    <div class="col-xl-3"></div>
    <div class="col-xl-6 mb-4">
        <h5>Thông tin tài sản và nợ tại thời điểm hiện tại</h5>
    </div>
    <div class="col-xl-3"></div>
</div>

<div class="row">
    <div class="col-xl-3"></div>
    <div class="col-xl-6 mb-4">
        <div class="accordion" id="accordionExample">
            <div class="card">
                <div class="card-header" id="headingOne">
                    <h5 class="mb-0">
                        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne"
                            aria-expanded="true" aria-controls="collapseOne">
                            Tài sản
                        </button>
                    </h5>
                </div>

                <div id="collapseOne" class="collapse show" aria-labelledby="headingOne"
                    data-parent="#accordionExample">
                    <div class="card-body">
                        <ul class="list-group">
                            {% for a in list_assets %}
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                {{a.name}}
                                <span class="badge badge-primary badge-pill">{{a.amount}}</span>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header" id="headingTwo">
                    <h5 class="mb-0">
                        <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                            data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            Nợ
                        </button>
                    </h5>
                </div>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                    <div class="card-body">
                        <ul class="list-group">
                            {% for l in list_liabilities %}
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                {{l.name}}
                                <span class="badge badge-primary badge-pill">{{l.amount}}</span>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3"></div>
</div>



<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    const ctx = document.getElementById('net_asset_history_data_chart').getContext('2d');

    var chart_data = JSON.parse('{{ chart_data | safe}}');

    var dataset = [
        {
            label: 'Tài sản ròng',
            data: chart_data.map(function (e) {
                console.log("ee: ", e)
                return e.net
            }),
            stack: 'combined',
            type: 'bar'
        },
        {
            label: 'Tài sản',
            data: chart_data.map(function (e) {
                return e.asset
            }),
            stack: 'combined'
        },
        {
            label: 'Nợ',
            data: chart_data.map(function (e) {
                return e.liability
            }),
            stack: 'combined'
        }
    ]


    const config = {
        type: 'line',
        data: {
            labels: chart_data.map(function (e) {
                return e.month
            }),
            datasets: dataset
        },
        options: {
            plugins: {
                title: {
                    display: true,
                    text: 'Tài sản ròng theo tháng'
                }
            },
            scales: {
                y: {
                    stacked: true
                }
            }
        },
    };

    new Chart(ctx, config);
</script>

{% endblock %}

source/asset/templates/asset/new_activity.html
{% extends 'layouts/default/page.html' %}

{% load bootstrap4 %}
{% load i18n %}

{% block content %}

<h4>Thêm hoạt động</h4>


<form method="post" id="acticty-form-id" data-cities-url="{% url 'asset:ajax_load_category' %}" class="form-horizontal"
    novalidate>

    {% csrf_token %}
    {% bootstrap_form form layout="horizontal" %}

    <button class="btn btn-primary">Thêm</button>

</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_activity_type").change(function () {
        var url = $("#acticty-form-id").attr("data-cities-url");
        var activity_type = $(this).val();

        $.ajax({
            url: url,
            data: {
                'activity_type': activity_type
            },
            success: function (data) {
                $("#id_category").html(data);
            }
        });

        if (activity_type == "INCOME") {
            $("#id_funding_sources").html('<option value="CASH" selected="">Tiền mặt</option>')
        } else {
            $("#id_funding_sources").html('<option value="CASH" selected="">Tiền mặt</option><option value="CREDIT CARD">Thẻ tín dụng</option><option value="SHORT-TERM DEBT">Khoản nợ ngắn hạn</option><option value="LONG-TERM DEBT">Khoản nợ giải hạn</option>')
        }
    });

    (function ($, undefined) {

        "use strict";

        // When ready.
        $(function () {

            var $form = $("#acticty-form-id");
            var $input = $form.find("#id_amount_0");

            $input.on("keyup", function (event) {


                // When user select text in the document, also abort.
                var selection = window.getSelection().toString();
                if (selection !== '') {
                    return;
                }

                // When the arrow keys are pressed, abort.
                if ($.inArray(event.keyCode, [38, 40, 37, 39]) !== -1) {
                    return;
                }


                var $this = $(this);

                // Get the value.
                var input = $this.val();

                var input = input.replace(/[\D\s\._\-]+/g, "");
                input = input ? parseInt(input, 10) : 0;

                $this.val(function () {
                    return (input === 0) ? "" : input.toLocaleString("en-US");
                });
            });

            /**
             * ==================================
             * When Form Submitted
             * ==================================
             */
            $form.on("submit", function (event) {
                var rawNumber = $("#id_amount_0").val().replace(/[($)\s\,_\-]+/g, '')
                $("#id_amount_0").val(rawNumber)
            });

        });
    })(jQuery);
</script>


{% endblock %}